---
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.4.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
      - id: debug-statements
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: end-of-file-fixer

  # yaml

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint

  # ruby

  - repo: https://github.com/rubocop/rubocop
    rev: v1.44.1
    hooks:
      - id: rubocop
