#!/usr/bin/env ruby

require 'oxidized/script/cli'

# Override the original behavior
# See https://github.com/mixigroup/oxidized-mix for details
require 'oxidized_mix'

debug = ARGV.include?('-d') || ARGV.include?('--debug')

begin
  cli = OxidizedMix::Oxidized::Script::CLI.new

  Oxidized::Config.load_custom cli.extra_config
  Oxidized.mgr = Oxidized::Manager.new
  Oxidized.mgr.load_custom_models

  cli.run
rescue StandardError => e
  warn e
  raise if debug

  exit 1
end
